import * as path from "path";

export const CHARSET = "utf-8";
export const ROOT_DIR = path.resolve(__dirname, "..");
export const SRC_DIR = path.resolve(ROOT_DIR, "src");
export const THEMES_DIR = path.resolve(ROOT_DIR, "themes");
export const THEME_HEADER_CONTENT =
  "// This file was generated by running the build script from the package root. \n// Do not edit it directly.\n";
